FROM ruby:2.5.4-alpine
LABEL maintainer "Guillaume Briday <guillaumebriday@gmail.com>"

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ --no-cache \
  nodejs \
  nodejs-npm \
  yarn
