FROM ruby:2.3-alpine@sha256:60c44723f12848e72d9b87efbb00cff4e5d34fec9520e0692e26e181f54302be
LABEL maintainer "Guillaume Briday <guillaumebriday@gmail.com>"

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ --no-cache \
  nodejs \
  nodejs-npm \
  yarn
